### ISSUE TITLE
RC01 in AP mode can not be added into intergration

### ISSUE THREAD

**Issue by skr3328** [JuanManuelRomeroGarcia/hass-miwifi#1]
I have 3 RC01 in use, the main router is used as AP and the other 2 are used in mesh mode. I modified the enum.py  to add support for RC01,and the 2 meshed router now can be added in MiWiFi integration. However  the RC01 in AP mode keeps saying 'NoneType' object has no attribute 'name'. Here is the log, hopefully somebody can fix this.

AttributeError: 'NoneType' object has no attribute 'name'
2025-03-28 16:00:29,396 - ERROR - Unexpected error fetching MiWifi updater data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miwifi/updater.py", line 291, in update
    await self._async_prepare(method, self.data)
  File "/config/custom_components/miwifi/updater.py", line 436, in _async_prepare
    await action(data)
  File "/config/custom_components/miwifi/updater.py", line 917, in _async_prepare_device_list
    self.add_device(device, action=action, integrations=integrations)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miwifi/updater.py", line 1084, in add_device
    code: str = _device.get(ATTR_TRACKER_CONNECTION, Connection.LAN).name.replace(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by JuanManuelRomeroGarcia** [comment]
Update INTEGRATION to MIWIFI XIAOHACK EDITION 3.0.3

**Comment by skr3328** [comment]
Thank you, the problem solved after updating to 3.0.3. Please add RN04 in enum.py. The only prolem I have now  is the 5G and 5G game channel are unknow for  RC01.


![Image](https://github.com/user-attachments/assets/234a54ba-8782-4cb7-ae09-3eb7862ee6d8)

**Comment by JuanManuelRomeroGarcia** [comment]
Add RN04, Can you send me logos related to the RC01's 5G gaming antennas so I can find the problem?

**Comment by skr3328** [comment]
01 01:18:23.172 WARNING (MainThread) [miwifi] Primary endpoint failed load qnetwork/get_netmode
2025-04-01 01:18:30.409 WARNING (MainThread) [miwifi] Error connecting to router (attempt #1 of 10): LuciConnectionError('Connection error')

I see no log related to  the 5G channel .

**Comment by JuanManuelRomeroGarcia** [comment]
Can you go to /config/custom_components/miwifi/Logs and check if there are any errors with the game antennas?
